<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Crud_Application_With_Gridview.aspx.cs" Inherits="CRUD_Application_With_Gridview.Crud_Application_With_Gridview" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            font-size: larger;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>

            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSource1" ShowFooter="True" Width="805px" CssClass="auto-style1" Height="228px">
                <Columns>
                    <asp:TemplateField HeaderText="Id" InsertVisible="False" SortExpression="Id">
                        <EditItemTemplate>
                            <asp:Label ID="lbl_Id" runat="server" Text='<%# Eval("Id") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_Id" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:LinkButton ID="LinkBtnInsert" runat="server" OnClick="LinkBtnInsert_Click" ValidationGroup="Insert" Font-Size="Larger">Insert</asp:LinkButton>
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Name" SortExpression="Name">
                        <EditItemTemplate>
                            <asp:TextBox ID="Txt_Name" runat="server" Text='<%# Bind("Name") %>' Font-Size="Medium"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidatorName" ControlToValidate="Txt_Name" runat="server" ForeColor="Red" Text="*" SetFocusOnError="true" ErrorMessage="Name is required" Font-Size="Medium"></asp:RequiredFieldValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_Name" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="Footer_Txt_Name" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidatorFooterName" ValidationGroup="Insert" ControlToValidate="Footer_Txt_Name" runat="server" ForeColor="Red" Text="*" SetFocusOnError="true" ErrorMessage="Name is required" Font-Size="Medium"></asp:RequiredFieldValidator>
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Gender" SortExpression="Gender">
                        <EditItemTemplate>
                            <asp:DropDownList ID="Edit_DDL_Gender" runat="server" Text='<%# Bind("Gender") %>' Font-Size="Medium">
                                <asp:ListItem>Select Gender</asp:ListItem>
                                <asp:ListItem>Male</asp:ListItem>
                                <asp:ListItem>Female</asp:ListItem>
                            </asp:DropDownList>
                            <asp:RequiredFieldValidator InitialValue="Select Gender" ID="RequiredFieldValidatorGender" ControlToValidate="Edit_DDL_Gender" runat="server" ForeColor="Red" Text="*" SetFocusOnError="true" ErrorMessage="Gender is required" Font-Size="Medium"></asp:RequiredFieldValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_Gender" runat="server" Text='<%# Bind("Gender") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:DropDownList ID="Footer_DDL_Gender" runat="server">
                                <asp:ListItem>Select Gender</asp:ListItem>
                                <asp:ListItem>Male</asp:ListItem>
                                <asp:ListItem>Female</asp:ListItem>
                            </asp:DropDownList>
                            <asp:RequiredFieldValidator InitialValue="Select Gender" ID="RequiredFieldValidatorFooterGender" ValidationGroup="Insert" ControlToValidate="Footer_DDL_Gender" runat="server" ForeColor="Red" Text="*" SetFocusOnError="true" ErrorMessage="Gender is required" Font-Size="Medium"></asp:RequiredFieldValidator>
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Class" SortExpression="Class">
                        <EditItemTemplate>
                            <asp:TextBox ID="txt_Class" runat="server" Text='<%# Bind("Class") %>' Font-Size="Medium"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidatorClass" ControlToValidate="txt_Class" runat="server" ForeColor="Red" Text="*" SetFocusOnError="true" ErrorMessage="Class is required" Font-Size="Medium"></asp:RequiredFieldValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbl_Class" runat="server" Text='<%# Bind("Class") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="Footer_Txt_Class" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidatorFooterClass" ValidationGroup="Insert" ControlToValidate="Footer_Txt_Class" runat="server" ForeColor="Red" Text="*" SetFocusOnError="true" ErrorMessage="Class is required" Font-Size="Medium"></asp:RequiredFieldValidator>
                        </FooterTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
                <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
                <RowStyle BackColor="White" ForeColor="#330099" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                <SortedAscendingCellStyle BackColor="#FEFCEB" />
                <SortedAscendingHeaderStyle BackColor="#AF0101" />
                <SortedDescendingCellStyle BackColor="#F6F0C0" />
                <SortedDescendingHeaderStyle BackColor="#7E0000" />
            </asp:GridView>

            <%-- Validation Summary --%>

            <asp:ValidationSummary ID="ValidationSummaryInsert" ValidationGroup="Insert" runat="server" BorderColor="#CCCCCC" Font-Size="Larger" ForeColor="#FF3300" />
            <asp:ValidationSummary ID="ValidationSummaryGridview" runat="server" BorderColor="#CCCCCC" Font-Size="Larger" ForeColor="#FF3300" />
            <br />

            <%-- DataSource code --%>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Student_Details] WHERE [Id] = @Id" InsertCommand="INSERT INTO [Student_Details] ([Name], [Gender], [Class]) VALUES (@Name, @Gender, @Class)" SelectCommand="SELECT * FROM [Student_Details]" UpdateCommand="UPDATE [Student_Details] SET [Name] = @Name, [Gender] = @Gender, [Class] = @Class WHERE [Id] = @Id">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Gender" Type="String" />
                    <asp:Parameter Name="Class" Type="Int32" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Gender" Type="String" />
                    <asp:Parameter Name="Class" Type="Int32" />
                    <asp:Parameter Name="Id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />

        </div>
    </form>
</body>
</html>
